#!/bin/bash

# find all sources but ignore auto generated code
files=$(find kiwi test/unit -name "*.py" -type f | grep -v xml_parse.py)

# IGNORE="E..." # Ignore check
# IGNORE="$IGNORE,E..." # Another check to ignore

IGNORE="E501" # ignore line too long, ok for docopt usage

pep8 -v --statistics --ignore="$IGNORE" $files
