# -*- coding: utf-8 -*-
#
# kiwi documentation build configuration file, created by
# sphinx-quickstart on Fri Feb  5 11:03:18 2016.
#
import sys
import os

extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinxcontrib.spelling',
]


spelling_lang='en_US'
spelling_show_suggestions = True
spelling_ignore_pypi_package_names = True
# spelling_word_list_filename='spelling_wordlist.txt'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['.templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# The man page toctree documents.
kiwi_doc = 'kiwi'
result_list_doc = 'result_list'
result_bundle_doc = 'result_bundle'
system_prepare_doc = 'system_prepare'
system_update_doc = 'system_update'
system_build_doc = 'system_build'
system_create_doc = 'system_create'

# General information about the project.
project = u'kiwi'
copyright = u'2016, Marcus Schäfer'
author = u'Marcus Schäfer'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'8'
# The full version, including alpha/beta/rc tags.
release = u'1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        kiwi_doc,
        'kiwi', u'Creating Operating System Images',
        [author],
        2
    ),
    (
        result_list_doc,
        'kiwi::result::list',
        u'List build results',
        [author],
        2
    ),
    (
        result_bundle_doc,
        'kiwi::result::bundle',
        u'Bundle build results',
        [author],
        2
    ),
    (
        system_prepare_doc,
        'kiwi::system::prepare',
        u'Prepare image root system',
        [author],
        2
    ),
    (
        system_create_doc,
        'kiwi::system::create',
        u'Create image from prepared root system',
        [author],
        2
    ),
    (
        system_update_doc,
        'kiwi::system::update',
        u'Update/Upgrade image root system',
        [author],
        2
    ),
    (
        system_build_doc,
        'kiwi::system::build',
        u'Build image in combined prepare and create step',
        [author],
        2
    )
]

# If true, show URL addresses after external links.
#man_show_urls = False
