#!/bin/bash
#================
# FILE          : preinit
#----------------
# PROJECT       : openSUSE KIWI Image System
# COPYRIGHT     : (c) 2006 SUSE LINUX Products GmbH. All rights reserved
#               :
# AUTHOR        : Marcus Schaefer <ms@suse.de>
#               :
# BELONGS TO    : Operating System images
#               :
# DESCRIPTION   : This file is called after the image root
#               : has changed by the linuxrc script
#               :
# STATUS        : BETA
#----------------
#======================================
# Functions...
#--------------------------------------
. /include

#======================================
# 1) start error log
#--------------------------------------
errorLogStart
Echo "Calling pre-init stage in system image"

#======================================
# 2) check for LOCAL_BOOT
#--------------------------------------
if [ "$LOCAL_BOOT" = "yes" ];then
    exit 0
fi

#======================================
# 3) start udev
#--------------------------------------
mountSystemFilesystems
udevSystemStart

#======================================
# 4) update mount table
#--------------------------------------
updateMTAB

#======================================
# 5) create framebuffer devices
#--------------------------------------
createFramebufferDevices

#======================================
# 6) check preinit services
#--------------------------------------
if isVirtioDevice;then
    runPreinitServices virtio
fi
if isDASDDevice;then
    runPreinitServices dasd
fi
if isZFCPDevice;then
    runPreinitServices zfcp
fi

#======================================
# 7) create initrd on diskful
#--------------------------------------
if [ -z "$UNIONFS_CONFIG" ]; then
    #======================================
    # use distro initrd tool
    #--------------------------------------
    setupInitrd
else
    #======================================
    # use kiwi initrd from RW partition
    #--------------------------------------
    bootLoaderOK=1
fi

#======================================
# 8) Install boot loader if ok
#--------------------------------------
if [ $bootLoaderOK = 1 ];then
    installBootLoader
fi

#======================================
# 9) setup console
#--------------------------------------
setupConsole

#======================================
# 10) load network module
#--------------------------------------
if loadNetworkCardS390 "0.0.0191";then
    #======================================
    # 10.2) Setup network interface and DNS
    #--------------------------------------
    setupNetworkInterfaceS390
    udevPending
    setupNetworkStatic 1
    setupNetworkStatic 0
fi

#======================================
# 11) Run user script
#--------------------------------------
runHook preCallInit

#======================================
# 12) kill udev
#--------------------------------------
udevSystemStop
umountSystemFilesystems
