#!/usr/bin/python
"""
usage: kiwicompat -h | --help
       kiwicompat --prepare=<description> --root=<image-root>
           [--recycle-root]
           [--logfile=<filename>]
           [--set-repo=<uri>]
           [--set-repoalias=<alias>]
           [--set-repopriority=<priority>]
           [--set-repotype=<type>]
           [--add-repo=<uri>...]
           [--add-repoalias=<alias>...]
           [--add-repopriority=<priority>...]
           [--add-repotype=<type>...]
           [--debug]
       kiwicompat --create=<image-root> --dest-dir=<destination>
           [--type=<image-type>]
           [--logfile=<filename>]
           [--debug]
       kiwicompat --upgrade=<image-root>
           [--add-package=<name>...]
           [--del-package=<name>...]
           [--logfile=<filename>]
           [--debug]
       kiwicompat -v | --version

options:
    -p | --prepare
    -c | --create
    -d | --dest-dir
    -t | --type
    -u | --upgrade
    -l | --logfile
    -v --version
"""

import sys
import logging
from docopt import docopt
from docopt import DocoptExit


class Cli(object):
    """
        Compatibility class for old style kiwi calls
    """
    def __init__(self):
        try:
            self.compat_args = docopt(
                __doc__, options_first=True
            )
        except DocoptExit as e:
            message_header = '\n'.join(
                [
                    'The provided legacy kiwi commandline is invalid',
                    'or not supported. Plase check the following usage',
                    'information if you just mistyped the call:'
                ]
            )
            message_footer = '\n'.join(
                [
                    'In case of a correct legacy kiwi command but not',
                    'supported by kiwicompat, please contact us via the',
                    'github issue system at:\n',
                    'https://github.com/SUSE/kiwi/issues'
                ]
            )
            raise NotImplementedError(
                '%s\n\n%s\n\n%s' %
                (message_header, format(e), message_footer)
            )


class Translate(object):
    def __init__(self, arguments):
        self.arguments = arguments
        # TODO: translate into new kiwi call and exec
        print self.arguments


logging.basicConfig(format='%(message)s')

try:
    app = Cli()
    Translate(app.compat_args)
except NotImplementedError as e:
    logging.error(format(e))
