d /srv/tftpboot 0755 tftp tftp
d /srv/tftpboot/KIWI 0755 tftp tftp
d /srv/tftpboot/pxelinux.cfg 0755 tftp tftp
d /srv/tftpboot/image 0755 tftp tftp
d /srv/tftpboot/upload 0755 tftp tftp
d /srv/tftpboot/boot 0755 tftp tftp
