# Copyright (c) 2019 SUSE Linux GmbH.  All rights reserved.
#
# This file is part of kiwi.
#
# kiwi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# kiwi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kiwi.  If not, see <http://www.gnu.org/licenses/>
#

import os
from textwrap import dedent
from typing import (
    List, Dict
)

# project
from kiwi.storage.subformat.vagrant_base import DiskFormatVagrantBase, VagrantConfigDict
from kiwi.storage.subformat.vmdk import DiskFormatVmdk
from kiwi.command import Command


class DiskFormatVagrantVMware(DiskFormatVagrantBase):
    """
    Base class for creating vagrant boxes.

    The documentation of the vagrant box format can be found here:
    https://www.vagrantup.com/docs/boxes/format.html
    In a nutshell, a vagrant box is a tar, tar.gz or zip archive of the
    following:

    1. ``metadata.json``:
       A json file that contains the name of the provider
       and arbitrary additional data (that vagrant doesn't care about).
    2. ``Vagrantfile``:
       A Vagrantfile which defines the boxes' MAC address. It
       can be also used to define other settings of the box, e.g.
       the method via which the ``/vagrant/`` directory is shared.
       This file is either automatically generated by KIWI or we use a file
       that has been provided by the user (depends on the setting in
       `vagrantconfig.embebbed_vagrantfile`)
    3. The actual virtual disk image: this is provider specific and
       vagrant simply forwards it to your virtual machine provider.

    Required methods/variables that child classes must implement:

    * :meth:`vagrant_post_init`

      post initializing method that has to specify the vagrant
      provider name in :attr:`provider` and the box name in
      :attr:`image_format`. Note: new providers also needs to
      be specified in the schema and the box name needs to be
      registered to :func:`kiwi.defaults.Defaults.get_disk_format_types`

    * :meth:`create_box_img`

    Optional methods:

    * :meth:`get_additional_metadata`
    * :meth:`get_additional_vagrant_config_settings`

    """

    """
    **Create a vagrant box for the vmware provider**
    """

    def vagrant_post_init(self, custom_args: VagrantConfigDict) -> None:
        self.image_format = 'vagrant.vmware_desktop.box'
        self.provider = 'vmware_desktop'
        self.options = self.get_qemu_option_list(custom_args)

    def create_box_img(self, temp_image_dir: str) -> List[str]:
        """
        Creates the vmdk disk image for the vmware_desktop vagrant provider

        :param str temp_image_dir:
            Path to the temporary directory used to build the box image

        :return:
            A list of files relevant for the libvirt box to be
            included in the vagrant box

        :rtype: list
        """
        vmdk = DiskFormatVmdk(
            self.xml_state, self.root_dir, self.target_dir,
            custom_args=self.options
        )
        vmdk.create_image_format()
        box_image = os.sep.join([temp_image_dir, 'box.img'])
        Command.run(
            [
                'mv', self.get_target_file_path_for_format(vmdk.image_format),
                box_image
            ]
        )
        return [box_image]

    def get_additional_metadata(self) -> Dict:
        """
        Provide box metadata needed to create the box in vagrant

        :return:
            Returns a dictionary containing the virtual image format
            and the size of the image.

        :rtype: dict
        """
        return {
            'format': 'vmdk'
        }

    def get_additional_vagrant_config_settings(self) -> str:
        """
        Returns settings for the libvirt provider telling vagrant to use kvm.

        :return:
            ruby code to be evaluated as string

        :rtype: str
        """
        # return dedent('''
        #     config.vm.synced_folder ".", "/vagrant", type: "rsync"
        #     config.vm.provider :libvirt do |libvirt|
        #       libvirt.driver = "kvm"
        #     end
        # ''').strip()
        return ''
