name: 'Mark stale issues and PRs with the stale label'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. stale label was set.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed as part of the community meeting.'
          days-before-stale: 60
          days-before-pr-close: -1
          days-before-issue-close: -1
