name: CI-Test-PyPI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: '0'
    strategy:
      matrix:
        python-version: ["3.11"]

    environment:
      name: pypi
      url: https://pypi.org/p/kiwi

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Python${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.7.1
    - name: Prepare
      run: |
        poetry build --version
        printenv SOURCE_DATE_EPOCH
        stat .bumpversion.cfg
        make prepare_for_pypi
        tar -tvf dist/*.tar.gz
